### ISSUE TITLE
Initiates websocket handshake, connects, send a messages then closes the connection and crashes and restarts the whole initiation

### ISSUE THREAD

**Issue by Greger312** [pollev/python-websocket-proxy#3]
After adding the certificates to the browser it gets a bit further, but as soon as it tunnels a websocket messages it crashes and closes the connection:

> py websocket_http_proxy.py
> started https intercept proxy server at 127.0.0.1 (port 9999)
> Initiating websocket handshake
> 127.0.0.1 - - [24/Jan/2024 16:26:28] "GET / HTTP/1.1" 101 -
> 127.0.0.1 - - [24/Jan/2024 16:26:28] websocket connected
> 127.0.0.1 - - [24/Jan/2024 16:26:28] Connecting to remote websocket wss://@@@@@@@@@@@/
> 127.0.0.1 - - [24/Jan/2024 16:26:28] Starting thread to forward server messages to the client
> CLIENT: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
> Exception in thread Thread-9 (forward_to_client):
> Traceback (most recent call last):
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
>     self.run()
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\@@@@@@@@@@@\websocket_http_proxy.py", line 625, in forward_to_client
>     message = str(proxy_obj._remote_websocket.recv())
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\@@@\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 388, in recv
>     opcode, data = self.recv_data()
>                    ^^^^^^^^^^^^^^^^
>   File "C:\Users\@@@\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 416, in recv_data
>     opcode, frame = self.recv_data_frame(control_frame)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\@@@\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 437, in recv_data_frame
>     frame = self.recv_frame()
>             ^^^^^^^^^^^^^^^^^
>   File "C:\Users\@@@\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 478, in recv_frame
>     return self.frame_buffer.recv_frame()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\@@@\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_abnf.py", line 363, in recv_frame
>     self.recv_header()
>   File "C:\Users\@@@\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_abnf.py", line 319, in recv_header
>     header = self.recv_strict(2)
>              ^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\@@@\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_abnf.py", line 398, in recv_strict
>     bytes_ = self.recv(min(16384, shortage))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\@@@\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_core.py", line 563, in _recv
>     return recv(self.sock, bufsize)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\@@@\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\websocket\_socket.py", line 129, in recv
>     raise WebSocketConnectionClosedException("Connection to remote host was lost.")
> websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
> 

Is this something on my side, something else I'm missing or whats going on?

**Comment by pollev** [comment]
Sorry I really can't say.. From your error log it looks like the remote server (that you are connecting to) is dropping the connection as soon as you start listening on the web-socket. Why this happens I cannot tell. You'll have to do some debugging of your own or try mitmproxy as I told you before.

**Comment by Greger312** [comment]
I've tried using mitmproxy and burpsuit, those works fine, I'm just trying to get something more minimalistic to work which doesn't require a whole setup like those two.

Do you have a discord or something? Would you like to help me trouble shoot, I'm a bit out of my experience level it feels like.

**Comment by pollev** [comment]
Sorry bud, gonna be brutally honest here, this is not some heavily maintained open source project. It's something I made because I had a need for it and then opened it on github for anyone else to use.

But I have a full time job and limited free time that I won't spend debugging other peoples projects (I don't even have time to debug my own 😀). I hope you understand.
